### ISSUE TITLE
Definition de la home de composer

### ISSUE THREAD

**Issue by pchabbert** [le-phare/ansible-deploy#36]
Par default, pour ansible,  c'est `~/.composer` hors, dans la version 2 de composer, la home est soit dans `XDG_CONFIG_HOME` soit `~/.config/composer`

Ce qui pose soucis lors de l'authentification (via le auth.json) packagist.

**Comment by pierreboissinot** [comment]
@pchabbert lephare/ansible-deploy écrit  `auth.json` en fonction de la configuration du remote server via le fact `composer_facts.home` .  Ce fact est défini par `config/steps/gather_facts.yml`:

```
- name: LEPHARE - Set facts
  set_fact:
    php_facts:
      version: "{{ php_version.stdout }}"
      extensions: "{{ php_extensions.stdout_lines }}"
    composer_facts:
      home: "{{ lookup('env', 'COMPOSER_HOME') | default('~/.composer', true) }}"
```

On lit la variable d'environnement `COMPOSER_HOME` définie sur le remote server, 
si la variable n'est pas définie, le fact `composer_facts.home` est donc par défaut '~/.composer'.
Cela semble être le cas que tu rencontres.

Le fact est ensuite utilisé pour écrire l' `auth.json`

`config/steps/composer/private_registry.yml`:
```
- name: LEPHARE | COMPOSER | Ensure configuration directory exists
  file:
    path: "{{ composer_facts.home }}"
    state: directory
    recurse: yes
    mode: 0755
  register: composer_home_directory
```

Je ne crois pas que ce soit lié à Composer 2, cela viendrait de la variable d'environnement COMPOSER_HOME définie par la distro du remote serveur.

Dans ce cas, il faudrait l'override dans le playbook ou le `hosts` file (c'est ce que je fait).
